import { NextResponse } from "next/server";
import { cors } from "../_lib";

export const runtime = "nodejs";

// Full app catalog (generated). Each app carries its connection style ("auth"): oauth → browser
// flow; api_key/bearer/basic → in-app credential modal; none → connect directly. Public, no auth.
const APPS = [
  { slug: "GMAIL", name: "Gmail", cat: "email", auth: "oauth" },
  { slug: "GITHUB", name: "GitHub", cat: "developer", auth: "oauth" },
  { slug: "GOOGLECALENDAR", name: "Google Calendar", cat: "scheduling", auth: "oauth" },
  { slug: "NOTION", name: "Notion", cat: "notes", auth: "oauth" },
  { slug: "GOOGLESHEETS", name: "Google Sheets", cat: "spreadsheets", auth: "oauth" },
  { slug: "SLACK", name: "Slack", cat: "chat", auth: "oauth" },
  { slug: "SUPABASE", name: "Supabase", cat: "developer", auth: "oauth" },
  { slug: "OUTLOOK", name: "Outlook", cat: "email", auth: "oauth" },
  { slug: "PERPLEXITYAI", name: "Perplexity AI", cat: "ai", auth: "api_key" },
  { slug: "TWITTER", name: "Twitter", cat: "social", auth: "oauth" },
  { slug: "GOOGLEDRIVE", name: "Google Drive", cat: "storage", auth: "oauth" },
  { slug: "GOOGLEDOCS", name: "Google Docs", cat: "documents", auth: "oauth" },
  { slug: "HUBSPOT", name: "HubSpot", cat: "crm", auth: "oauth" },
  { slug: "LINEAR", name: "Linear", cat: "project", auth: "oauth" },
  { slug: "AIRTABLE", name: "Airtable", cat: "productivity", auth: "oauth" },
  { slug: "CODEINTERPRETER", name: "Code Interpreter", cat: "developer", auth: "none" },
  { slug: "SERPAPI", name: "SerpApi", cat: "analytics", auth: "api_key" },
  { slug: "JIRA", name: "Jira", cat: "project", auth: "oauth" },
  { slug: "FIRECRAWL", name: "Firecrawl", cat: "scraping", auth: "api_key" },
  { slug: "TAVILY", name: "Tavily", cat: "scraping", auth: "api_key" },
  { slug: "YOUTUBE", name: "YouTube", cat: "video", auth: "oauth" },
  { slug: "SLACKBOT", name: "Slackbot", cat: "chat", auth: "oauth" },
  { slug: "CANVAS", name: "Canvas", cat: "education", auth: "oauth" },
  { slug: "BITBUCKET", name: "Bitbucket", cat: "developer", auth: "oauth" },
  { slug: "GOOGLETASKS", name: "Google Tasks", cat: "tasks", auth: "oauth" },
  { slug: "DISCORD", name: "Discord", cat: "chat", auth: "oauth" },
  { slug: "FIGMA", name: "Figma", cat: "design", auth: "oauth" },
  { slug: "REDDIT", name: "Reddit", cat: "social", auth: "oauth" },
  { slug: "CAL", name: "Cal", cat: "scheduling", auth: "api_key" },
  { slug: "WRIKE", name: "Wrike", cat: "project", auth: "oauth" },
  { slug: "EXA", name: "Exa", cat: "analytics", auth: "api_key" },
  { slug: "SENTRY", name: "Sentry", cat: "developer", auth: "oauth" },
  { slug: "SNOWFLAKE", name: "Snowflake", cat: "database", auth: "oauth" },
  { slug: "HACKERNEWS", name: "Hacker News", cat: "news", auth: "none" },
  { slug: "ELEVENLABS", name: "ElevenLabs", cat: "ai", auth: "api_key" },
  { slug: "MICROSOFT_TEAMS", name: "Microsoft Teams", cat: "chat", auth: "oauth" },
  { slug: "ASANA", name: "Asana", cat: "project", auth: "oauth" },
  { slug: "PEOPLEDATALABS", name: "People Data Labs", cat: "analytics", auth: "api_key" },
  { slug: "SHOPIFY", name: "Shopify", cat: "ecommerce", auth: "api_key" },
  { slug: "LINKEDIN", name: "LinkedIn", cat: "social", auth: "oauth" },
  { slug: "GOOGLE_MAPS", name: "Google Maps", cat: "developer", auth: "oauth" },
  { slug: "ONE_DRIVE", name: "OneDrive", cat: "storage", auth: "oauth" },
  { slug: "DOCUSIGN", name: "DocuSign", cat: "signatures", auth: "oauth" },
  { slug: "DISCORDBOT", name: "Discord Bot", cat: "chat", auth: "oauth" },
  { slug: "SALESFORCE", name: "Salesforce", cat: "crm", auth: "oauth" },
  { slug: "CALENDLY", name: "Calendly", cat: "scheduling", auth: "oauth" },
  { slug: "TRELLO", name: "Trello", cat: "project", auth: "oauth" },
  { slug: "APOLLO", name: "Apollo", cat: "crm", auth: "api_key" },
  { slug: "SEMRUSH", name: "Semrush", cat: "marketing", auth: "api_key" },
  { slug: "MEM0", name: "Mem0", cat: "ai", auth: "api_key" },
  { slug: "NEON", name: "Neon", cat: "database", auth: "api_key" },
  { slug: "WEATHERMAP", name: "OpenWeatherMap", cat: "developer", auth: "none" },
  { slug: "POSTHOG", name: "PostHog", cat: "analytics", auth: "api_key" },
  { slug: "CLICKUP", name: "ClickUp", cat: "productivity", auth: "oauth" },
  { slug: "BREVO", name: "Brevo", cat: "marketing", auth: "api_key" },
  { slug: "STRIPE", name: "Stripe", cat: "payments", auth: "api_key" },
  { slug: "KLAVIYO", name: "Klaviyo", cat: "marketing", auth: "api_key" },
  { slug: "BROWSERBASE_TOOL", name: "Browserbase", cat: "developer", auth: "api_key" },
  { slug: "MAILCHIMP", name: "Mailchimp", cat: "marketing", auth: "oauth" },
  { slug: "ATTIO", name: "Attio", cat: "crm", auth: "oauth" },
  { slug: "GOOGLEMEET", name: "Google Meet", cat: "meetings", auth: "oauth" },
  { slug: "TEXT_TO_PDF", name: "Text to PDF", cat: "documents", auth: "none" },
  { slug: "ZOHO", name: "Zoho", cat: "crm", auth: "oauth" },
  { slug: "FIREFLIES", name: "Fireflies", cat: "other", auth: "api_key" },
  { slug: "DROPBOX", name: "Dropbox", cat: "storage", auth: "oauth" },
  { slug: "SHORTCUT", name: "Shortcut", cat: "project", auth: "api_key" },
  { slug: "CONFLUENCE", name: "Confluence", cat: "other", auth: "oauth" },
  { slug: "FRESHDESK", name: "Freshdesk", cat: "crm", auth: "api_key" },
  { slug: "BORNEO", name: "Borneo", cat: "other", auth: "api_key" },
  { slug: "MIXPANEL", name: "Mixpanel", cat: "analytics", auth: "basic" },
  { slug: "CODA", name: "Coda", cat: "productivity", auth: "api_key" },
  { slug: "ACCULYNX", name: "Acculynx", cat: "crm", auth: "api_key" },
  { slug: "AHREFS", name: "Ahrefs", cat: "marketing", auth: "api_key" },
  { slug: "AFFINITY", name: "Affinity", cat: "crm", auth: "api_key" },
  { slug: "AMPLITUDE", name: "Amplitude", cat: "analytics", auth: "api_key" },
  { slug: "HEYGEN", name: "HeyGen", cat: "ai", auth: "api_key" },
  { slug: "AGENCYZOOM", name: "AgencyZoom", cat: "crm", auth: "api_key" },
  { slug: "GOOGLEBIGQUERY", name: "Google BigQuery", cat: "database", auth: "oauth" },
  { slug: "MICROSOFT_CLARITY", name: "Microsoft Clarity", cat: "analytics", auth: "api_key" },
  { slug: "COINBASE", name: "Coinbase", cat: "developer", auth: "api_key" },
  { slug: "MONDAY", name: "Monday", cat: "project", auth: "oauth" },
  { slug: "SEMANTICSCHOLAR", name: "Semantic Scholar", cat: "ai", auth: "api_key" },
  { slug: "SENDGRID", name: "SendGrid", cat: "other", auth: "api_key" },
  { slug: "JUNGLESCOUT", name: "Jungle Scout", cat: "ecommerce", auth: "api_key" },
  { slug: "PIPEDRIVE", name: "Pipedrive", cat: "crm", auth: "oauth" },
  { slug: "BAMBOOHR", name: "BambooHR", cat: "other", auth: "oauth" },
  { slug: "WHATSAPP", name: "WhatsApp", cat: "other", auth: "oauth" },
  { slug: "DYNAMICS365", name: "Dynamics 365", cat: "crm", auth: "oauth" },
  { slug: "ZENDESK", name: "Zendesk", cat: "crm", auth: "oauth" },
  { slug: "GOOGLEPHOTOS", name: "Google Photos", cat: "design", auth: "oauth" },
  { slug: "LMNT", name: "LMNT", cat: "ai", auth: "api_key" },
  { slug: "METAADS", name: "Meta Ads", cat: "other", auth: "oauth" },
  { slug: "ZENROWS", name: "ZenRows", cat: "scraping", auth: "api_key" },
  { slug: "GOOGLESUPER", name: "Google Super", cat: "storage", auth: "oauth" },
  { slug: "BROWSER_TOOL", name: "Browser Tool", cat: "ai", auth: "none" },
  { slug: "YOUSEARCH", name: "You.com", cat: "ai", auth: "api_key" },
  { slug: "LINKUP", name: "Linkup", cat: "scraping", auth: "api_key" },
  { slug: "LISTENNOTES", name: "Listen Notes", cat: "video", auth: "api_key" },
  { slug: "TYPEFULLY", name: "Typefully", cat: "other", auth: "api_key" },
  { slug: "BOLNA", name: "Bolna", cat: "ai", auth: "api_key" },
  { slug: "ROCKETLANE", name: "Rocketlane", cat: "project", auth: "api_key" },
  { slug: "ZOOM", name: "Zoom", cat: "meetings", auth: "oauth" },
  { slug: "ONEPAGE", name: "Onepage", cat: "productivity", auth: "bearer" },
  { slug: "ENTELLIGENCE", name: "Entelligence", cat: "ai", auth: "none" },
  { slug: "RETELLAI", name: "Retell AI", cat: "ai", auth: "api_key" },
  { slug: "SERVICENOW", name: "ServiceNow", cat: "other", auth: "basic" },
  { slug: "GOOGLEADS", name: "Google Ads", cat: "other", auth: "oauth" },
  { slug: "PAGERDUTY", name: "PagerDuty", cat: "other", auth: "oauth" },
  { slug: "TONEDEN", name: "Toneden", cat: "other", auth: "api_key" },
  { slug: "RAFFLYS", name: "Rafflys", cat: "other", auth: "api_key" },
  { slug: "FINAGE", name: "Finage", cat: "analytics", auth: "api_key" },
  { slug: "FOMO", name: "Fomo", cat: "marketing", auth: "api_key" },
  { slug: "BANNERBEAR", name: "Bannerbear", cat: "design", auth: "api_key" },
  { slug: "MIRO", name: "Miro", cat: "other", auth: "oauth" },
  { slug: "SHARE_POINT", name: "SharePoint", cat: "documents", auth: "oauth" },
  { slug: "MOCEAN", name: "Mocean", cat: "other", auth: "api_key" },
  { slug: "FORMCARRY", name: "Formcarry", cat: "forms", auth: "api_key" },
  { slug: "APPDRAG", name: "AppDrag", cat: "developer", auth: "api_key" },
  { slug: "METATEXTAI", name: "Metatextai", cat: "ai", auth: "api_key" },
  { slug: "BREEZY_HR", name: "Breezy Hr", cat: "other", auth: "oauth" },
  { slug: "LAUNCH_DARKLY", name: "LaunchDarkly", cat: "developer", auth: "api_key" },
  { slug: "MAILERLITE", name: "MailerLite", cat: "marketing", auth: "api_key" },
  { slug: "CONTENTFUL", name: "Contentful", cat: "developer", auth: "oauth" },
  { slug: "CLOSE", name: "Close", cat: "crm", auth: "api_key" },
  { slug: "DOCMOSIS", name: "Docmosis", cat: "documents", auth: "api_key" },
  { slug: "ABLY", name: "Ably", cat: "developer", auth: "api_key" },
  { slug: "MORE_TREES", name: "More Trees", cat: "news", auth: "api_key" },
  { slug: "NETSUITE", name: "Netsuite", cat: "finance", auth: "oauth" },
  { slug: "MOZ", name: "Moz", cat: "marketing", auth: "api_key" },
  { slug: "RECALLAI", name: "Recall.ai", cat: "other", auth: "api_key" },
  { slug: "APALEO", name: "Apaleo", cat: "scheduling", auth: "oauth" },
  { slug: "SURVEY_MONKEY", name: "SurveyMonkey", cat: "forms", auth: "oauth" },
  { slug: "ZOHO_BOOKS", name: "Zoho Books", cat: "finance", auth: "oauth" },
  { slug: "ZOHO_INVENTORY", name: "Zoho Inventory", cat: "finance", auth: "oauth" },
  { slug: "FACEBOOK", name: "Facebook", cat: "social", auth: "oauth" },
  { slug: "TINYPNG", name: "TinyPNG", cat: "design", auth: "api_key" },
  { slug: "MOPINION", name: "Mopinion", cat: "analytics", auth: "api_key" },
  { slug: "CRUSTDATA", name: "Crustdata", cat: "other", auth: "api_key" },
  { slug: "WEBEX", name: "Webex", cat: "meetings", auth: "oauth" },
  { slug: "BRANDFETCH", name: "Brandfetch", cat: "design", auth: "api_key" },
  { slug: "CANVA", name: "Canva", cat: "design", auth: "oauth" },
  { slug: "DIGICERT", name: "Digicert", cat: "other", auth: "api_key" },
  { slug: "DAILYBOT", name: "Dailybot", cat: "other", auth: "api_key" },
  { slug: "LINKHUT", name: "Linkhut", cat: "other", auth: "oauth" },
  { slug: "DROPBOX_SIGN", name: "Dropbox Sign", cat: "signatures", auth: "api_key" },
  { slug: "TIMELY", name: "Timely", cat: "other", auth: "oauth" },
  { slug: "BOX", name: "Box", cat: "storage", auth: "oauth" },
  { slug: "SMUGMUG", name: "SmugMug", cat: "design", auth: "api_key" },
  { slug: "PRODUCTBOARD", name: "Productboard", cat: "other", auth: "api_key" },
  { slug: "BLACKBAUD", name: "Blackbaud", cat: "other", auth: "oauth" },
  { slug: "WEBFLOW", name: "Webflow", cat: "other", auth: "oauth" },
  { slug: "AMCARDS", name: "Amcards", cat: "marketing", auth: "api_key" },
  { slug: "SIMPLESAT", name: "Simplesat", cat: "crm", auth: "api_key" },
  { slug: "FLUTTERWAVE", name: "Flutterwave", cat: "payments", auth: "api_key" },
  { slug: "HACKERRANK_WORK", name: "HackerRank Work", cat: "developer", auth: "api_key" },
  { slug: "FRESHBOOKS", name: "FreshBooks", cat: "finance", auth: "oauth" },
  { slug: "PROCESS_STREET", name: "Process Street", cat: "tasks", auth: "api_key" },
  { slug: "SCREENSHOTONE", name: "ScreenshotOne", cat: "developer", auth: "api_key" },
  { slug: "CHATWORK", name: "Chatwork", cat: "chat", auth: "api_key" },
  { slug: "KLIPFOLIO", name: "Klipfolio", cat: "other", auth: "api_key" },
  { slug: "DEMIO", name: "Demio", cat: "other", auth: "api_key" },
  { slug: "ALTOVIZ", name: "Altoviz", cat: "finance", auth: "api_key" },
  { slug: "D2LBRIGHTSPACE", name: "D2L Brightspace", cat: "other", auth: "oauth" },
  { slug: "BLACKBOARD", name: "Blackboard", cat: "other", auth: "oauth" },
  { slug: "LEVER", name: "Lever", cat: "other", auth: "api_key" },
  { slug: "ZOHO_BIGIN", name: "Zoho Bigin", cat: "crm", auth: "oauth" },
  { slug: "PANDADOC", name: "PandaDoc", cat: "documents", auth: "api_key" },
  { slug: "WORKIOM", name: "Workiom", cat: "productivity", auth: "api_key" },
  { slug: "LEXOFFICE", name: "Lexoffice", cat: "finance", auth: "api_key" },
  { slug: "GORGIAS", name: "Gorgias", cat: "crm", auth: "api_key" },
  { slug: "GOOGLE_ANALYTICS", name: "Google Analytics", cat: "analytics", auth: "oauth" },
  { slug: "TODOIST", name: "Todoist", cat: "tasks", auth: "oauth" },
  { slug: "ZOHO_DESK", name: "Zoho Desk", cat: "crm", auth: "oauth" },
  { slug: "ASHBY", name: "Ashby", cat: "other", auth: "api_key" },
  { slug: "DATAROBOT", name: "DataRobot", cat: "ai", auth: "api_key" },
  { slug: "NGROK", name: "Ngrok", cat: "developer", auth: "api_key" },
  { slug: "SQUARE", name: "Square", cat: "payments", auth: "oauth" },
  { slug: "YANDEX", name: "Yandex", cat: "email", auth: "oauth" },
  { slug: "BASEROW", name: "Baserow", cat: "database", auth: "api_key" },
  { slug: "DIALPAD", name: "Dialpad", cat: "chat", auth: "oauth" },
  { slug: "FORMSITE", name: "Formsite", cat: "forms", auth: "api_key" },
  { slug: "YNAB", name: "YNAB", cat: "finance", auth: "oauth" },
  { slug: "KOMMO", name: "Kommo", cat: "crm", auth: "oauth" },
  { slug: "TISANE", name: "Tisane", cat: "ai", auth: "api_key" },
  { slug: "COINMARKETCAL", name: "CoinMarketCal", cat: "analytics", auth: "api_key" },
  { slug: "BROWSEAI", name: "Browseai", cat: "scraping", auth: "api_key" },
  { slug: "MAINTAINX", name: "Maintainx", cat: "tasks", auth: "api_key" },
  { slug: "TINYURL", name: "Tinyurl", cat: "other", auth: "api_key" },
  { slug: "BITWARDEN", name: "Bitwarden", cat: "other", auth: "oauth" },
  { slug: "EPIC_GAMES", name: "Epic Games", cat: "other", auth: "oauth" },
  { slug: "TIMECAMP", name: "TimeCamp", cat: "other", auth: "api_key" },
  { slug: "PIGGY", name: "Piggy", cat: "marketing", auth: "api_key" },
  { slug: "ALCHEMY", name: "Alchemy", cat: "developer", auth: "api_key" },
  { slug: "GUMROAD", name: "Gumroad", cat: "ecommerce", auth: "oauth" },
  { slug: "FOURSQUARE", name: "Foursquare", cat: "analytics", auth: "api_key" },
  { slug: "OPEN_SEA", name: "OpenSea", cat: "ecommerce", auth: "api_key" },
  { slug: "HUMANLOOP", name: "Humanloop", cat: "ai", auth: "api_key" },
  { slug: "ZOOMINFO", name: "Zoominfo", cat: "crm", auth: "oauth" },
  { slug: "GONG", name: "Gong", cat: "analytics", auth: "basic" },
  { slug: "PLACEKEY", name: "Placekey", cat: "analytics", auth: "api_key" },
  { slug: "DATAGMA", name: "Datagma", cat: "analytics", auth: "api_key" },
  { slug: "SERVICEM8", name: "Servicem8", cat: "scheduling", auth: "oauth" },
  { slug: "TEXTRAZOR", name: "TextRazor", cat: "ai", auth: "api_key" },
  { slug: "BUBBLE", name: "Bubble", cat: "other", auth: "api_key" },
  { slug: "CHMEETINGS", name: "Chmeetings", cat: "other", auth: "api_key" },
  { slug: "CLOUDFLARE", name: "Cloudflare", cat: "other", auth: "api_key" },
  { slug: "HARVEST", name: "Harvest", cat: "other", auth: "oauth" },
  { slug: "WAKATIME", name: "WakaTime", cat: "other", auth: "oauth" },
  { slug: "XERO", name: "Xero", cat: "finance", auth: "oauth" },
  { slug: "BOLDSIGN", name: "Boldsign", cat: "signatures", auth: "oauth" },
  { slug: "ACTIVE_CAMPAIGN", name: "ActiveCampaign", cat: "marketing", auth: "api_key" },
  { slug: "ZOHO_MAIL", name: "Zoho Mail", cat: "email", auth: "oauth" },
  { slug: "MURAL", name: "Mural", cat: "other", auth: "oauth" },
  { slug: "BREX", name: "Brex", cat: "finance", auth: "oauth" },
  { slug: "INTERCOM", name: "Intercom", cat: "support", auth: "oauth" },
  { slug: "HIGHLEVEL", name: "Highlevel", cat: "marketing", auth: "oauth" },
  { slug: "EVENTBRITE", name: "Eventbrite", cat: "other", auth: "oauth" },
  { slug: "BEEMINDER", name: "Beeminder", cat: "tasks", auth: "api_key" },
  { slug: "ROCKET_REACH", name: "RocketReach", cat: "crm", auth: "api_key" },
  { slug: "INTERZOID", name: "Interzoid", cat: "analytics", auth: "api_key" },
  { slug: "EXIST", name: "Exist", cat: "analytics", auth: "oauth" },
  { slug: "ZENSERP", name: "Zenserp", cat: "scraping", auth: "api_key" },
  { slug: "ZOHO_INVOICE", name: "Zoho Invoice", cat: "other", auth: "oauth" },
  { slug: "STACK_EXCHANGE", name: "Stack Exchange", cat: "developer", auth: "oauth" },
  { slug: "BOTBABA", name: "Botbaba", cat: "other", auth: "api_key" },
  { slug: "DATADOG", name: "Datadog", cat: "other", auth: "oauth" },
  { slug: "WABOXAPP", name: "Waboxapp", cat: "other", auth: "api_key" },
  { slug: "ECHTPOST", name: "Echtpost", cat: "documents", auth: "api_key" },
  { slug: "_1PASSWORD", name: "1password", cat: "other", auth: "api_key" },
  { slug: "_21RISK", name: "21risk", cat: "other", auth: "api_key" },
  { slug: "_2CHAT", name: "2chat", cat: "chat", auth: "api_key" },
  { slug: "ABSTRACT", name: "Abstract", cat: "developer", auth: "api_key" },
  { slug: "ABUSELPDB", name: "AbuseIPDB", cat: "other", auth: "api_key" },
  { slug: "ABYSSALE", name: "Abyssale", cat: "design", auth: "api_key" },
  { slug: "ACCREDIBLE_CERTIFICATES", name: "Accredible certificates", cat: "other", auth: "api_key" },
  { slug: "ACTIVE_TRAIL", name: "ActiveTrail", cat: "marketing", auth: "api_key" },
  { slug: "ADDRESSFINDER", name: "Addressfinder", cat: "developer", auth: "api_key" },
  { slug: "ADDRESSZEN", name: "Addresszen", cat: "developer", auth: "api_key" },
  { slug: "ADRAPID", name: "Adrapid", cat: "design", auth: "api_key" },
  { slug: "ADYNTEL", name: "Adyntel", cat: "other", auth: "api_key" },
  { slug: "AEROLEADS", name: "Aeroleads", cat: "other", auth: "api_key" },
  { slug: "AFFINDA", name: "Affinda", cat: "ai", auth: "api_key" },
  { slug: "AGENT_MAIL", name: "Agent Mail", cat: "ai", auth: "api_key" },
  { slug: "AGENTQL", name: "Agentql", cat: "scraping", auth: "api_key" },
  { slug: "AGENTY", name: "Agenty", cat: "scraping", auth: "api_key" },
  { slug: "AGILED", name: "Agiled", cat: "crm", auth: "api_key" },
  { slug: "AGILITY_CMS", name: "Agility CMS", cat: "other", auth: "api_key" },
  { slug: "AI_ML_API", name: "AI/ML API", cat: "ai", auth: "api_key" },
  { slug: "AIVOOV", name: "Aivoov", cat: "ai", auth: "api_key" },
  { slug: "ALGODOCS", name: "Algodocs", cat: "other", auth: "api_key" },
  { slug: "ALGOLIA", name: "Algolia", cat: "developer", auth: "api_key" },
  { slug: "ALL_IMAGES_AI", name: "All Images AI", cat: "ai", auth: "api_key" },
  { slug: "ALPACA", name: "Alpaca", cat: "other", auth: "api_key" },
  { slug: "ALPHA_VANTAGE", name: "Alpha Vantage", cat: "analytics", auth: "api_key" },
  { slug: "ALTTEXT_AI", name: "AltText.ai", cat: "ai", auth: "api_key" },
  { slug: "AMARA", name: "Amara", cat: "video", auth: "api_key" },
  { slug: "AMBEE", name: "Ambee", cat: "developer", auth: "api_key" },
  { slug: "AMBIENT_WEATHER", name: "Ambient Weather", cat: "other", auth: "api_key" },
  { slug: "ANCHOR_BROWSER", name: "Anchor Browser", cat: "ai", auth: "api_key" },
  { slug: "ANONYFLOW", name: "Anonyflow", cat: "other", auth: "api_key" },
  { slug: "ANTHROPIC_ADMINISTRATOR", name: "Anthropic Administrator", cat: "other", auth: "api_key" },
  { slug: "API_LABZ", name: "API Labz", cat: "ai", auth: "api_key" },
  { slug: "API_NINJAS", name: "API Ninjas", cat: "developer", auth: "api_key" },
  { slug: "API_SPORTS", name: "API-Sports", cat: "developer", auth: "api_key" },
  { slug: "API_BIBLE", name: "API.Bible", cat: "developer", auth: "api_key" },
  { slug: "API2PDF", name: "API2PDF", cat: "documents", auth: "api_key" },
  { slug: "APIFLASH", name: "Apiflash", cat: "design", auth: "api_key" },
  { slug: "APIFY", name: "Apify", cat: "scraping", auth: "api_key" },
  { slug: "APIFY_MCP", name: "Apify MCP", cat: "other", auth: "oauth" },
  { slug: "APILIO", name: "Apilio", cat: "other", auth: "api_key" },
  { slug: "APIPIE_AI", name: "APIpie AI", cat: "other", auth: "api_key" },
  { slug: "APIVERVE", name: "Apiverve", cat: "developer", auth: "api_key" },
  { slug: "APPCIRCLE", name: "Appcircle", cat: "developer", auth: "api_key" },
  { slug: "APPOINTO", name: "Appointo", cat: "scheduling", auth: "api_key" },
  { slug: "APPVEYOR", name: "Appveyor", cat: "developer", auth: "api_key" },
  { slug: "ARYN", name: "Aryn", cat: "other", auth: "api_key" },
  { slug: "ASCORA", name: "Ascora", cat: "crm", auth: "api_key" },
  { slug: "ASIN_DATA_API", name: "ASIN Data API", cat: "ecommerce", auth: "api_key" },
  { slug: "ASTICA_AI", name: "Astica AI", cat: "ai", auth: "api_key" },
  { slug: "ASYNC_INTERVIEW", name: "Async Interview", cat: "other", auth: "api_key" },
  { slug: "AUTOBOUND", name: "Autobound", cat: "other", auth: "api_key" },
  { slug: "AUTOM", name: "Autom", cat: "scraping", auth: "api_key" },
  { slug: "AYRSHARE", name: "Ayrshare", cat: "other", auth: "api_key" },
  { slug: "BACKENDLESS", name: "Backendless", cat: "developer", auth: "api_key" },
  { slug: "BART", name: "Bart", cat: "developer", auth: "api_key" },
  { slug: "BASECAMP", name: "Basecamp", cat: "project", auth: "oauth" },
  { slug: "BASELINKER", name: "Baselinker", cat: "ecommerce", auth: "api_key" },
  { slug: "BASIN", name: "Basin", cat: "forms", auth: "api_key" },
  { slug: "BEACONCHAIN", name: "beaconcha.in", cat: "analytics", auth: "api_key" },
  { slug: "BEACONSTAC", name: "Beaconstac", cat: "marketing", auth: "api_key" },
  { slug: "BEAMER", name: "Beamer", cat: "other", auth: "api_key" },
  { slug: "BENCH", name: "Bench", cat: "developer", auth: "none" },
  { slug: "BENCHMARK_EMAIL", name: "Benchmark Email", cat: "marketing", auth: "api_key" },
  { slug: "BENZINGA", name: "Benzinga", cat: "analytics", auth: "api_key" },
  { slug: "BESTBUY", name: "Bestbuy", cat: "ecommerce", auth: "api_key" },
  { slug: "BETTER_PROPOSALS", name: "Better Proposals", cat: "other", auth: "api_key" },
  { slug: "BETTER_STACK", name: "Better Stack", cat: "other", auth: "api_key" },
  { slug: "BETTERCONTACT", name: "Bettercontact", cat: "other", auth: "api_key" },
  { slug: "BIDSKETCH", name: "Bidsketch", cat: "other", auth: "api_key" },
  { slug: "BIG_DATA_CLOUD", name: "BigDataCloud", cat: "developer", auth: "api_key" },
  { slug: "BIGMAILER", name: "Bigmailer", cat: "marketing", auth: "api_key" },
  { slug: "BIGML", name: "Bigml", cat: "ai", auth: "api_key" },
  { slug: "BIGPICTURE_IO", name: "BigPicture.io", cat: "other", auth: "api_key" },
  { slug: "BITQUERY", name: "Bitquery", cat: "analytics", auth: "api_key" },
  { slug: "BLAZEMETER", name: "Blazemeter", cat: "developer", auth: "basic" },
  { slug: "BLOCKNATIVE", name: "Blocknative", cat: "developer", auth: "api_key" },
  { slug: "BOLOFORMS", name: "Boloforms", cat: "signatures", auth: "api_key" },
  { slug: "BOLT_IOT", name: "Bolt Iot", cat: "other", auth: "api_key" },
  { slug: "BONSAI", name: "Bonsai", cat: "database", auth: "basic" },
  { slug: "BOOKINGMOOD", name: "Bookingmood", cat: "scheduling", auth: "api_key" },
  { slug: "BOOQABLE", name: "Booqable", cat: "scheduling", auth: "api_key" },
  { slug: "BOTPRESS", name: "Botpress", cat: "other", auth: "api_key" },
  { slug: "BOTSONIC", name: "Botsonic", cat: "other", auth: "api_key" },
  { slug: "BOTSTAR", name: "Botstar", cat: "other", auth: "api_key" },
  { slug: "BOUNCER", name: "Bouncer", cat: "email", auth: "api_key" },
  { slug: "BOXHERO", name: "Boxhero", cat: "other", auth: "api_key" },
  { slug: "BREATHEHR", name: "Breathe HR", cat: "other", auth: "api_key" },
  { slug: "BREEZE", name: "Breeze", cat: "project", auth: "api_key" },
  { slug: "BRIGHTDATA", name: "Bright Data", cat: "scraping", auth: "api_key" },
  { slug: "BRILLIANT_DIRECTORIES", name: "Brilliant Directories", cat: "other", auth: "api_key" },
  { slug: "BROWSERLESS", name: "Browserless", cat: "developer", auth: "api_key" },
  { slug: "BTCPAY_SERVER", name: "BTCPay Server", cat: "payments", auth: "api_key" },
  { slug: "BUGBUG", name: "Bugbug", cat: "developer", auth: "api_key" },
  { slug: "BUGHERD", name: "Bugherd", cat: "project", auth: "api_key" },
  { slug: "BUGSNAG", name: "Bugsnag", cat: "developer", auth: "api_key" },
  { slug: "BUILDKITE", name: "Buildkite", cat: "developer", auth: "api_key" },
  { slug: "BUILTWITH", name: "BuiltWith", cat: "analytics", auth: "api_key" },
  { slug: "BUNNYCDN", name: "BunnyCDN", cat: "developer", auth: "api_key" },
  { slug: "BYTEFORMS", name: "Byteforms", cat: "forms", auth: "api_key" },
  { slug: "CABINPANDA", name: "Cabinpanda", cat: "forms", auth: "api_key" },
  { slug: "CALENDARHERO", name: "CalendarHero", cat: "scheduling", auth: "api_key" },
  { slug: "CALLERAPI", name: "Callerapi", cat: "other", auth: "api_key" },
  { slug: "CALLINGLY", name: "Callingly", cat: "other", auth: "api_key" },
  { slug: "CALLPAGE", name: "Callpage", cat: "other", auth: "api_key" },
  { slug: "CAMPAIGN_CLEANER", name: "Campaign Cleaner", cat: "email", auth: "api_key" },
  { slug: "CAMPAYN", name: "Campayn", cat: "marketing", auth: "api_key" },
  { slug: "CANNY", name: "Canny", cat: "other", auth: "api_key" },
  { slug: "CAPSULE_CRM", name: "Capsule CRM", cat: "crm", auth: "oauth" },
  { slug: "CARBONE", name: "Carbone", cat: "documents", auth: "api_key" },
  { slug: "CARDLY", name: "Cardly", cat: "marketing", auth: "api_key" },
  { slug: "CASTINGWORDS", name: "Castingwords", cat: "other", auth: "api_key" },
  { slug: "CATS", name: "Cats", cat: "design", auth: "api_key" },
  { slug: "CDR_PLATFORM", name: "Cdr Platform", cat: "developer", auth: "api_key" },
  { slug: "CELIGO", name: "Celigo", cat: "developer", auth: "api_key" },
  { slug: "CENSUS_BUREAU", name: "Census Bureau", cat: "analytics", auth: "api_key" },
  { slug: "CENTRALSTATIONCRM", name: "CentralStationCRM", cat: "crm", auth: "api_key" },
  { slug: "CERTIFIER", name: "Certifier", cat: "documents", auth: "api_key" },
  { slug: "CHASER", name: "Chaser", cat: "finance", auth: "api_key" },
  { slug: "CHATBOTKIT", name: "Chatbotkit", cat: "other", auth: "api_key" },
  { slug: "CHATFAI", name: "Chatfai", cat: "other", auth: "api_key" },
  { slug: "CINCOPA", name: "Cincopa", cat: "video", auth: "api_key" },
  { slug: "CIRCLECI", name: "CircleCI", cat: "developer", auth: "api_key" },
  { slug: "CLAID_AI", name: "Claid.ai", cat: "design", auth: "api_key" },
  { slug: "CLASSMARKER", name: "Classmarker", cat: "other", auth: "api_key" },
  { slug: "CLEAROUT", name: "Clearout", cat: "email", auth: "api_key" },
  { slug: "CLICKHOUSE", name: "ClickHouse", cat: "database", auth: "basic" },
  { slug: "CLICKMEETING", name: "Clickmeeting", cat: "other", auth: "api_key" },
  { slug: "CLICKSEND", name: "ClickSend", cat: "other", auth: "basic" },
  { slug: "CLIENTARY", name: "Clientary", cat: "project", auth: "api_key" },
  { slug: "CLOCKIFY", name: "Clockify", cat: "other", auth: "api_key" },
  { slug: "CLOUDCART", name: "Cloudcart", cat: "ecommerce", auth: "api_key" },
  { slug: "CLOUDCONVERT", name: "CloudConvert", cat: "storage", auth: "api_key" },
  { slug: "CLOUDFLARE_API_KEY", name: "Cloudflare Api Key", cat: "other", auth: "api_key" },
  { slug: "CLOUDFLARE_BROWSER_RENDERING", name: "Cloudflare Browser Rendering", cat: "scraping", auth: "api_key" },
  { slug: "CLOUDINARY", name: "Cloudinary", cat: "design", auth: "api_key" },
  { slug: "CLOUDLAYER", name: "Cloudlayer", cat: "documents", auth: "api_key" },
  { slug: "CLOUDPRESS", name: "Cloudpress", cat: "documents", auth: "api_key" },
  { slug: "COASSEMBLE", name: "Coassemble", cat: "education", auth: "api_key" },
  { slug: "CODACY", name: "Codacy", cat: "developer", auth: "api_key" },
  { slug: "CODEMAGIC", name: "Codemagic", cat: "developer", auth: "api_key" },
  { slug: "CODEREADR", name: "Codereadr", cat: "developer", auth: "api_key" },
  { slug: "CODY", name: "Cody", cat: "other", auth: "api_key" },
  { slug: "COINMARKETCAP", name: "CoinMarketCap", cat: "analytics", auth: "api_key" },
  { slug: "COINRANKING", name: "Coinranking", cat: "analytics", auth: "api_key" },
  { slug: "COLLEGE_FOOTBALL_DATA", name: "College Football Data", cat: "analytics", auth: "api_key" },
  { slug: "COMMCARE", name: "CommCare", cat: "forms", auth: "api_key" },
  { slug: "COMPANYENRICH", name: "Companyenrich", cat: "developer", auth: "api_key" },
  { slug: "CONNECTEAM", name: "Connecteam", cat: "other", auth: "api_key" },
  { slug: "CONSTANT_CONTACT", name: "Constant Contact", cat: "marketing", auth: "oauth" },
  { slug: "CONTENTFUL_GRAPHQL", name: "Contentful Graphql", cat: "developer", auth: "api_key" },
  { slug: "CONTROL_D", name: "Control D", cat: "other", auth: "api_key" },
  { slug: "CONVERSION_TOOLS", name: "Conversion Tools", cat: "documents", auth: "api_key" },
  { slug: "CONVERTAPI", name: "Convertapi", cat: "documents", auth: "api_key" },
  { slug: "CONVEX", name: "Convex", cat: "developer", auth: "api_key" },
  { slug: "CONVEYOR", name: "Conveyor", cat: "other", auth: "api_key" },
  { slug: "CONVOLO_AI", name: "Convolo AI", cat: "other", auth: "api_key" },
  { slug: "CORRENTLY", name: "Corrently", cat: "analytics", auth: "api_key" },
  { slug: "COUNTDOWN_API", name: "Countdown API", cat: "ecommerce", auth: "api_key" },
  { slug: "COUPA", name: "Coupa", cat: "finance", auth: "oauth" },
  { slug: "CRAFTMYPDF", name: "Craftmypdf", cat: "documents", auth: "api_key" },
  { slug: "CROWDIN", name: "Crowdin", cat: "developer", auth: "api_key" },
  { slug: "CROWTERMINAL", name: "CrowTerminal", cat: "developer", auth: "api_key" },
  { slug: "CULTS", name: "Cults", cat: "ecommerce", auth: "api_key" },
  { slug: "CURATED", name: "Curated", cat: "marketing", auth: "api_key" },
  { slug: "CURRENCYSCOOP", name: "CurrencyScoop", cat: "developer", auth: "api_key" },
  { slug: "CURRENTS_API", name: "Currents API", cat: "news", auth: "api_key" },
  { slug: "CURSOR", name: "Cursor", cat: "developer", auth: "api_key" },
  { slug: "CUSTOMERIO", name: "Customer.io", cat: "marketing", auth: "api_key" },
  { slug: "CUSTOMGPT", name: "Customgpt", cat: "other", auth: "api_key" },
  { slug: "CUSTOMJS", name: "Customjs", cat: "developer", auth: "api_key" },
  { slug: "CUTT_LY", name: "Cutt.ly", cat: "other", auth: "api_key" },
  { slug: "DADATA_RU", name: "DaData.ru", cat: "developer", auth: "api_key" },
  { slug: "DAFFY", name: "Daffy", cat: "other", auth: "api_key" },
  { slug: "DART", name: "Dart", cat: "project", auth: "oauth" },
  { slug: "DATA247", name: "Data247", cat: "developer", auth: "api_key" },
  { slug: "DATABOX", name: "Databox", cat: "analytics", auth: "api_key" },
  { slug: "DATABRICKS", name: "Databricks", cat: "developer", auth: "oauth" },
  { slug: "DATAFORSEO", name: "Dataforseo", cat: "developer", auth: "basic" },
  { slug: "DATASCOPE", name: "Datascope", cat: "forms", auth: "api_key" },
  { slug: "DEADLINE_FUNNEL", name: "Deadline Funnel", cat: "marketing", auth: "api_key" },
  { slug: "DEEPGRAM", name: "Deepgram", cat: "ai", auth: "api_key" },
  { slug: "DEEPIMAGE", name: "DeepImage", cat: "ai", auth: "api_key" },
  { slug: "DEEPSEEK", name: "DeepSeek", cat: "other", auth: "api_key" },
  { slug: "DEEPWIKI_MCP", name: "DeepWiki MCP", cat: "other", auth: "none" },
  { slug: "DELIGHTED", name: "Delighted", cat: "forms", auth: "api_key" },
  { slug: "DEPLOYHQ", name: "DeployHQ", cat: "developer", auth: "basic" },
  { slug: "DESKTIME", name: "DeskTime", cat: "other", auth: "api_key" },
  { slug: "DETRACK", name: "Detrack", cat: "other", auth: "api_key" },
  { slug: "DEVTO", name: "DEV Community", cat: "developer", auth: "api_key" },
  { slug: "DEVIN_MCP", name: "Devin MCP", cat: "other", auth: "api_key" },
  { slug: "DIALMYCALLS", name: "Dialmycalls", cat: "chat", auth: "api_key" },
  { slug: "DICTIONARY_API", name: "Dictionary Api", cat: "other", auth: "api_key" },
  { slug: "DIFFBOT", name: "Diffbot", cat: "ai", auth: "api_key" },
  { slug: "DIGITAL_OCEAN", name: "DigitalOcean", cat: "developer", auth: "api_key" },
  { slug: "DNSFILTER", name: "Dnsfilter", cat: "other", auth: "api_key" },
  { slug: "DOCK_CERTS", name: "Dock Certs", cat: "other", auth: "api_key" },
  { slug: "DOCKER_HUB", name: "Docker Hub", cat: "developer", auth: "api_key" },
  { slug: "DOCNIFY", name: "Docnify", cat: "documents", auth: "api_key" },
  { slug: "DOCPARSER", name: "Docparser", cat: "documents", auth: "api_key" },
  { slug: "DOCRAPTOR", name: "DocRaptor", cat: "developer", auth: "api_key" },
  { slug: "DOCSAUTOMATOR", name: "Docsautomator", cat: "documents", auth: "api_key" },
  { slug: "DOCSBOT_AI", name: "DocsBot AI", cat: "other", auth: "api_key" },
  { slug: "DOCSUMO", name: "Docsumo", cat: "other", auth: "api_key" },
  { slug: "DOCUGENERATE", name: "Docugenerate", cat: "documents", auth: "api_key" },
  { slug: "DOCUMENSO", name: "Documenso", cat: "signatures", auth: "api_key" },
  { slug: "DOCUMINT", name: "Documint", cat: "documents", auth: "api_key" },
  { slug: "DOCUPILOT", name: "Docupilot", cat: "documents", auth: "api_key" },
  { slug: "DOCUPOST", name: "Docupost", cat: "documents", auth: "api_key" },
  { slug: "DOCUSEAL", name: "DocuSeal", cat: "signatures", auth: "api_key" },
  { slug: "DOPPLER", name: "Doppler", cat: "developer", auth: "api_key" },
  { slug: "DOPPLER_MARKETING_AUTOMATION", name: "Doppler Marketing Automation", cat: "marketing", auth: "api_key" },
  { slug: "DOPPLER_SECRETOPS", name: "Doppler SecretOps", cat: "developer", auth: "api_key" },
  { slug: "DOTSIMPLE", name: "Dotsimple", cat: "other", auth: "api_key" },
  { slug: "DOVETAIL", name: "Dovetail", cat: "analytics", auth: "api_key" },
  { slug: "DPD2", name: "Dpd2", cat: "ecommerce", auth: "api_key" },
  { slug: "DRAFTABLE", name: "Draftable", cat: "documents", auth: "api_key" },
  { slug: "DREAMSTUDIO", name: "Dreamstudio", cat: "ai", auth: "api_key" },
  { slug: "DRIPCEL", name: "Dripcel", cat: "marketing", auth: "api_key" },
  { slug: "DROMO", name: "Dromo", cat: "spreadsheets", auth: "api_key" },
  { slug: "DROPCONTACT", name: "Dropcontact", cat: "other", auth: "api_key" },
  { slug: "DUB", name: "Dub", cat: "other", auth: "api_key" },
  { slug: "DUNGEON_FIGHTER_ONLINE", name: "Dungeon Fighter Online", cat: "other", auth: "api_key" },
  { slug: "DYNAPICTURES", name: "Dynapictures", cat: "design", auth: "api_key" },
  { slug: "E2B", name: "E2b", cat: "developer", auth: "api_key" },
  { slug: "EAGLE_DOC", name: "Eagle doc", cat: "other", auth: "api_key" },
  { slug: "ECOLOGI", name: "Ecologi", cat: "news", auth: "api_key" },
  { slug: "EGNYTE", name: "Egnyte", cat: "storage", auth: "oauth" },
  { slug: "ELASTICSEARCH", name: "Elasticsearch", cat: "database", auth: "api_key" },
  { slug: "ELEVENREADER", name: "Elevenreader", cat: "ai", auth: "api_key" },
  { slug: "ELORUS", name: "Elorus", cat: "other", auth: "api_key" },
  { slug: "EMAILABLE", name: "Emailable", cat: "email", auth: "api_key" },
  { slug: "EMAILLISTVERIFY", name: "Emaillistverify", cat: "email", auth: "api_key" },
  { slug: "EMAILOCTOPUS", name: "EmailOctopus", cat: "marketing", auth: "api_key" },
  { slug: "EMELIA", name: "Emelia", cat: "other", auth: "api_key" },
  { slug: "ENCODIAN", name: "Encodian", cat: "documents", auth: "api_key" },
  { slug: "ENDORSAL", name: "Endorsal", cat: "other", auth: "api_key" },
  { slug: "ENGAGE", name: "Engage", cat: "marketing", auth: "basic" },
  { slug: "ENGINEMAILER", name: "Enginemailer", cat: "marketing", auth: "api_key" },
  { slug: "ENIGMA", name: "Enigma", cat: "other", auth: "api_key" },
  { slug: "EODHD_APIS", name: "EODHD APIs", cat: "analytics", auth: "api_key" },
  { slug: "ERPNEXT", name: "Erpnext", cat: "finance", auth: "api_key" },
  { slug: "ESIGNATURES_IO", name: "eSignatures.io", cat: "signatures", auth: "api_key" },
  { slug: "ESPOCRM", name: "Espocrm", cat: "crm", auth: "api_key" },
  { slug: "ESPUTNIK", name: "Esputnik", cat: "marketing", auth: "api_key" },
  { slug: "ETERMIN", name: "Etermin", cat: "scheduling", auth: "api_key" },
  { slug: "EVENIUM", name: "Evenium", cat: "other", auth: "api_key" },
  { slug: "EVENTEE", name: "Eventee", cat: "other", auth: "api_key" },
  { slug: "EVENTZILLA", name: "Eventzilla", cat: "other", auth: "api_key" },
  { slug: "EVERHOUR", name: "Everhour", cat: "other", auth: "api_key" },
  { slug: "EVERSIGN", name: "Eversign", cat: "signatures", auth: "api_key" },
  { slug: "EXCEL", name: "Excel", cat: "spreadsheets", auth: "oauth" },
  { slug: "EXPOFP", name: "Expofp", cat: "other", auth: "api_key" },
  { slug: "EXTRACTA_AI", name: "Extracta.ai", cat: "other", auth: "api_key" },
  { slug: "FACEUP", name: "Faceup", cat: "support", auth: "api_key" },
  { slug: "FAL_AI", name: "Fal.ai", cat: "other", auth: "api_key" },
  { slug: "FARADAY", name: "Faraday", cat: "ai", auth: "api_key" },
  { slug: "FATHOM", name: "Fathom", cat: "other", auth: "oauth" },
  { slug: "FEATHERY", name: "Feathery", cat: "forms", auth: "api_key" },
  { slug: "FELT", name: "Felt", cat: "developer", auth: "api_key" },
  { slug: "FIBERY", name: "Fibery", cat: "project", auth: "api_key" },
  { slug: "FIDEL_API", name: "Fidel API", cat: "developer", auth: "api_key" },
  { slug: "FILES_COM", name: "Files.com", cat: "storage", auth: "api_key" },
  { slug: "FILLOUT_FORMS", name: "Fillout Forms", cat: "forms", auth: "api_key" },
  { slug: "FINDYMAIL", name: "Findymail", cat: "email", auth: "api_key" },
  { slug: "FINERWORKS", name: "Finerworks", cat: "ecommerce", auth: "api_key" },
  { slug: "FINGERTIP", name: "Fingertip", cat: "other", auth: "api_key" },
  { slug: "FINMEI", name: "Finmei", cat: "finance", auth: "api_key" },
  { slug: "FIREBERRY", name: "Fireberry", cat: "crm", auth: "api_key" },
  { slug: "FIRMAO", name: "Firmao", cat: "crm", auth: "api_key" },
  { slug: "FIXER", name: "Fixer", cat: "developer", auth: "api_key" },
  { slug: "FIXER_IO", name: "Fixer.io", cat: "developer", auth: "api_key" },
  { slug: "FLEXISIGN", name: "Flexisign", cat: "signatures", auth: "api_key" },
  { slug: "FLOWISEAI", name: "Flowiseai", cat: "ai", auth: "api_key" },
  { slug: "FLUXGUARD", name: "Fluxguard", cat: "other", auth: "api_key" },
  { slug: "FLY", name: "Fly", cat: "developer", auth: "api_key" },
  { slug: "FOLK", name: "Folk", cat: "crm", auth: "api_key" },
  { slug: "FOLLOW_UP_BOSS", name: "Follow Up Boss", cat: "crm", auth: "api_key" },
  { slug: "FORCEMANAGER", name: "Forcemanager", cat: "crm", auth: "api_key" },
  { slug: "FORMBRICKS", name: "Formbricks", cat: "forms", auth: "api_key" },
  { slug: "FORMDESK", name: "Formdesk", cat: "forms", auth: "api_key" },
  { slug: "FRAUDLABS_PRO", name: "FraudLabs Pro", cat: "other", auth: "api_key" },
  { slug: "FREEAGENT", name: "Freeagent", cat: "finance", auth: "oauth" },
  { slug: "FRESHSERVICE", name: "Freshservice", cat: "support", auth: "api_key" },
  { slug: "FULLENRICH", name: "Fullenrich", cat: "other", auth: "api_key" },
  { slug: "GAGELIST", name: "Gagelist", cat: "developer", auth: "oauth" },
  { slug: "GAMMA", name: "Gamma", cat: "other", auth: "api_key" },
  { slug: "GAN_AI", name: "Gan.AI", cat: "ai", auth: "api_key" },
  { slug: "GATHERUP", name: "Gatherup", cat: "other", auth: "api_key" },
  { slug: "GEMINI", name: "Gemini", cat: "ai", auth: "none" },
  { slug: "GENDER_API", name: "Gender API", cat: "developer", auth: "api_key" },
  { slug: "GENDERAPI_IO", name: "GenderAPI.io", cat: "developer", auth: "api_key" },
  { slug: "GENDERIZE", name: "Genderize", cat: "developer", auth: "api_key" },
  { slug: "GEOAPIFY", name: "Geoapify", cat: "developer", auth: "api_key" },
  { slug: "GEOCODIO", name: "Geocodio", cat: "developer", auth: "api_key" },
  { slug: "GEOKEO", name: "Geokeo", cat: "developer", auth: "api_key" },
  { slug: "GETFORM", name: "Getform", cat: "forms", auth: "api_key" },
  { slug: "GETPROSPECT", name: "Getprospect", cat: "marketing", auth: "api_key" },
  { slug: "GIFT_UP", name: "Gift Up!", cat: "ecommerce", auth: "api_key" },
  { slug: "GIGASHEET", name: "Gigasheet", cat: "spreadsheets", auth: "api_key" },
  { slug: "GIPHY", name: "Giphy", cat: "design", auth: "api_key" },
  { slug: "GIST", name: "Gist", cat: "developer", auth: "api_key" },
  { slug: "GITEA", name: "Gitea", cat: "developer", auth: "api_key" },
  { slug: "GITLAB", name: "GitLab", cat: "developer", auth: "oauth" },
  { slug: "GIVEBUTTER", name: "Givebutter", cat: "other", auth: "api_key" },
  { slug: "GLADIA", name: "Gladia", cat: "other", auth: "api_key" },
  { slug: "GLEAP", name: "Gleap", cat: "support", auth: "api_key" },
  { slug: "GLOBALPING", name: "Globalping", cat: "other", auth: "api_key" },
  { slug: "GODIAL", name: "Godial", cat: "crm", auth: "api_key" },
  { slug: "GOODBITS", name: "Goodbits", cat: "marketing", auth: "api_key" },
  { slug: "GOODY", name: "Goody", cat: "ecommerce", auth: "api_key" },
  { slug: "GOOGLE_ADDRESS_VALIDATION", name: "Google Address Validation", cat: "developer", auth: "api_key" },
  { slug: "GOOGLE_ADMIN", name: "Google Admin", cat: "other", auth: "oauth" },
  { slug: "GOOGLE_CHAT", name: "Google Chat", cat: "productivity", auth: "oauth" },
  { slug: "GOOGLE_CLASSROOM", name: "Google Classroom", cat: "other", auth: "oauth" },
  { slug: "GOOGLE_CLOUD_VISION", name: "Google Cloud Vision", cat: "ai", auth: "api_key" },
  { slug: "GOOGLE_SEARCH_CONSOLE", name: "Google Search Console", cat: "analytics", auth: "oauth" },
  { slug: "GOOGLESLIDES", name: "Google Slides", cat: "documents", auth: "oauth" },
  { slug: "GOOGLECONTACTS", name: "Googlecontacts", cat: "productivity", auth: "oauth" },
  { slug: "GOOGLEFORMS", name: "Googleforms", cat: "productivity", auth: "oauth" },
  { slug: "GOSQUARED", name: "Gosquared", cat: "analytics", auth: "api_key" },
  { slug: "GRAFANA", name: "Grafana", cat: "developer", auth: "bearer" },
  { slug: "GRAFBASE", name: "Grafbase", cat: "developer", auth: "api_key" },
  { slug: "GRAPHHOPPER", name: "Graphhopper", cat: "developer", auth: "api_key" },
  { slug: "GRIPTAPE", name: "Griptape", cat: "ai", auth: "api_key" },
  { slug: "GRIST", name: "Grist", cat: "productivity", auth: "api_key" },
  { slug: "GROQCLOUD", name: "GroqCloud", cat: "other", auth: "api_key" },
  { slug: "GTMETRIX", name: "GTmetrix", cat: "developer", auth: "api_key" },
  { slug: "GUSTO", name: "Gusto", cat: "other", auth: "oauth" },
  { slug: "HABITICA", name: "Habitica", cat: "productivity", auth: "api_key" },
  { slug: "HANDWRYTTEN", name: "Handwrytten", cat: "marketing", auth: "api_key" },
  { slug: "HAPPY_SCRIBE", name: "Happy Scribe", cat: "other", auth: "api_key" },
  { slug: "HASHNODE", name: "Hashnode", cat: "developer", auth: "api_key" },
  { slug: "HEADOUT", name: "Headout", cat: "scheduling", auth: "api_key" },
  { slug: "HEARTBEAT", name: "Heartbeat", cat: "other", auth: "api_key" },
  { slug: "HELLOLEADS", name: "Helloleads", cat: "crm", auth: "api_key" },
  { slug: "HELP_SCOUT", name: "Help Scout", cat: "support", auth: "oauth" },
  { slug: "HELPDESK", name: "Helpdesk", cat: "support", auth: "api_key" },
  { slug: "HELPWISE", name: "Helpwise", cat: "support", auth: "api_key" },
  { slug: "HERE", name: "Here", cat: "developer", auth: "api_key" },
  { slug: "HEX", name: "Hex", cat: "analytics", auth: "api_key" },
  { slug: "HEYREACH", name: "Heyreach", cat: "marketing", auth: "api_key" },
  { slug: "HEYY", name: "Heyy", cat: "chat", auth: "api_key" },
  { slug: "HEYZINE", name: "Heyzine", cat: "documents", auth: "api_key" },
  { slug: "HIGHERGOV", name: "Highergov", cat: "other", auth: "api_key" },
  { slug: "HONEYBADGER", name: "Honeybadger", cat: "other", auth: "api_key" },
  { slug: "HONEYHIVE", name: "Honeyhive", cat: "ai", auth: "api_key" },
  { slug: "HOOKDECK", name: "Hookdeck", cat: "developer", auth: "api_key" },
  { slug: "HOSTINGER", name: "Hostinger", cat: "developer", auth: "api_key" },
  { slug: "HOTSPOTSYSTEM", name: "Hotspotsystem", cat: "other", auth: "api_key" },
  { slug: "HTML_TO_IMAGE", name: "HTML to Image", cat: "design", auth: "api_key" },
  { slug: "HUB_PLANNER", name: "Hub Planner", cat: "productivity", auth: "api_key" },
  { slug: "HUGGING_FACE", name: "Hugging Face", cat: "ai", auth: "api_key" },
  { slug: "HUMANITIX", name: "Humanitix", cat: "other", auth: "api_key" },
  { slug: "HUNTER", name: "Hunter", cat: "email", auth: "api_key" },
  { slug: "HYPEAUDITOR", name: "Hypeauditor", cat: "other", auth: "api_key" },
  { slug: "HYPERBROWSER", name: "Hyperbrowser", cat: "scraping", auth: "api_key" },
  { slug: "HYPERISE", name: "Hyperise", cat: "marketing", auth: "api_key" },
  { slug: "HYSTRUCT", name: "Hystruct", cat: "scraping", auth: "api_key" },
  { slug: "IBM_X_FORCE_EXCHANGE", name: "IBM X-Force Exchange", cat: "other", auth: "api_key" },
  { slug: "ICYPEAS", name: "Icypeas", cat: "email", auth: "api_key" },
  { slug: "IDENTITYCHECK", name: "Identitycheck", cat: "other", auth: "api_key" },
  { slug: "IGNISIGN", name: "Ignisign", cat: "signatures", auth: "api_key" },
  { slug: "IMAGEKIT_IO", name: "ImageKit", cat: "design", auth: "api_key" },
  { slug: "IMAGIOR", name: "Imagior", cat: "design", auth: "api_key" },
  { slug: "IMEJIS_IO", name: "Imejis.io", cat: "design", auth: "api_key" },
  { slug: "IMGBB", name: "ImgBB", cat: "design", auth: "api_key" },
  { slug: "IMGIX", name: "Imgix", cat: "design", auth: "api_key" },
  { slug: "INCIDENT_IO", name: "incident.io", cat: "developer", auth: "api_key" },
  { slug: "INFLUXDB_CLOUD", name: "InfluxDB Cloud", cat: "database", auth: "api_key" },
  { slug: "INSIGHTO_AI", name: "Insighto.ai", cat: "other", auth: "api_key" },
  { slug: "INSTACART", name: "Instacart", cat: "ecommerce", auth: "none" },
  { slug: "INSTAGRAM", name: "Instagram", cat: "social", auth: "oauth" },
  { slug: "INSTANTLY", name: "Instantly", cat: "other", auth: "api_key" },
  { slug: "INTELLIPRINT", name: "Intelliprint", cat: "documents", auth: "api_key" },
  { slug: "IP2LOCATION", name: "Ip2Location", cat: "developer", auth: "api_key" },
  { slug: "IP2LOCATION_IO", name: "IP2Location.io", cat: "developer", auth: "api_key" },
  { slug: "IP2PROXY", name: "Ip2Proxy", cat: "other", auth: "api_key" },
  { slug: "IP2WHOIS", name: "Ip2Whois", cat: "other", auth: "api_key" },
  { slug: "IPDATA_CO", name: "Ipdata.co", cat: "developer", auth: "api_key" },
  { slug: "IPINFO_IO", name: "Ipinfo.io", cat: "developer", auth: "api_key" },
  { slug: "IQAIR_AIRVISUAL", name: "Iqair Airvisual", cat: "developer", auth: "api_key" },
  { slug: "ITERABLE", name: "Iterable", cat: "marketing", auth: "api_key" },
  { slug: "JIGSAWSTACK", name: "Jigsawstack", cat: "ai", auth: "api_key" },
  { slug: "JOBNIMBUS", name: "JobNimbus", cat: "crm", auth: "api_key" },
  { slug: "JOTFORM", name: "Jotform", cat: "forms", auth: "api_key" },
  { slug: "JUMPCLOUD", name: "JumpCloud", cat: "other", auth: "api_key" },
  { slug: "KADOA", name: "Kadoa", cat: "scraping", auth: "api_key" },
  { slug: "KAGGLE", name: "Kaggle", cat: "ai", auth: "api_key" },
  { slug: "KALEIDO", name: "Kaleido", cat: "developer", auth: "api_key" },
  { slug: "KANBANIZE", name: "Kanbanize", cat: "project", auth: "api_key" },
  { slug: "KEEN_IO", name: "Keen.io", cat: "analytics", auth: "api_key" },
  { slug: "KEYWORD", name: "Keyword", cat: "marketing", auth: "api_key" },
  { slug: "KIBANA", name: "Kibana", cat: "analytics", auth: "api_key" },
  { slug: "KICKBOX", name: "Kickbox", cat: "email", auth: "api_key" },
  { slug: "KIEAI", name: "Kieai", cat: "ai", auth: "api_key" },
  { slug: "KIT", name: "Kit", cat: "marketing", auth: "oauth" },
  { slug: "KLAZIFY", name: "Klazify", cat: "developer", auth: "api_key" },
  { slug: "KNACK", name: "Knack", cat: "database", auth: "api_key" },
  { slug: "KO_FI", name: "Ko-fi", cat: "other", auth: "api_key" },
  { slug: "KONTENT_AI", name: "Kontent.ai", cat: "documents", auth: "api_key" },
  { slug: "KRAKEN_IO", name: "Kraken.io", cat: "design", auth: "api_key" },
  { slug: "L2S", name: "L2s", cat: "other", auth: "api_key" },
  { slug: "LAGROWTHMACHINE", name: "La Growth Machine", cat: "marketing", auth: "api_key" },
  { slug: "LABS64_NETLICENSING", name: "Labs64 NetLicensing", cat: "developer", auth: "api_key" },
  { slug: "LANDBOT", name: "Landbot", cat: "other", auth: "api_key" },
  { slug: "LANGBASE", name: "Langbase", cat: "ai", auth: "api_key" },
  { slug: "LAPOSTA", name: "Laposta", cat: "marketing", auth: "api_key" },
  { slug: "LEADBOXER", name: "LeadBoxer", cat: "analytics", auth: "api_key" },
  { slug: "LEADFEEDER", name: "Leadfeeder", cat: "analytics", auth: "api_key" },
  { slug: "LEADIQ", name: "LeadIQ", cat: "other", auth: "api_key" },
  { slug: "LEADOKU", name: "Leadoku", cat: "other", auth: "api_key" },
  { slug: "LEEXI", name: "Leexi", cat: "other", auth: "api_key" },
  { slug: "LEIGA", name: "Leiga", cat: "project", auth: "api_key" },
  { slug: "LEMLIST", name: "Lemlist", cat: "marketing", auth: "api_key" },
  { slug: "LEMON_SQUEEZY", name: "Lemon Squeezy", cat: "ecommerce", auth: "api_key" },
  { slug: "LESSONSPACE", name: "Lessonspace", cat: "other", auth: "api_key" },
  { slug: "LEVERLY", name: "Leverly", cat: "other", auth: "api_key" },
  { slug: "LINGUAPOP", name: "Linguapop", cat: "other", auth: "api_key" },
  { slug: "LINKEDIN_ADS", name: "Linkedin Ads", cat: "marketing", auth: "oauth" },
  { slug: "LINKLY", name: "Linkly", cat: "other", auth: "api_key" },
  { slug: "LISTCLEAN", name: "Listclean", cat: "email", auth: "api_key" },
  { slug: "LIVESESSION", name: "Livesession", cat: "analytics", auth: "api_key" },
  { slug: "LLMWHISPERER", name: "LLMWhisperer", cat: "other", auth: "api_key" },
  { slug: "LOB", name: "Lob", cat: "marketing", auth: "api_key" },
  { slug: "LODGIFY", name: "Lodgify", cat: "scheduling", auth: "api_key" },
  { slug: "LOGO_DEV", name: "Logo.dev", cat: "design", auth: "api_key" },
  { slug: "LOOMIO", name: "Loomio", cat: "project", auth: "api_key" },
  { slug: "LOOPS_SO", name: "Loops.so", cat: "email", auth: "api_key" },
  { slug: "LOYVERSE", name: "Loyverse", cat: "ecommerce", auth: "api_key" },
  { slug: "LUSHA", name: "Lusha", cat: "other", auth: "api_key" },
  { slug: "MAGNETIC", name: "Magnetic", cat: "project", auth: "api_key" },
  { slug: "MAILBLUSTER", name: "MailBluster", cat: "marketing", auth: "api_key" },
  { slug: "MAILBOXLAYER", name: "Mailboxlayer", cat: "email", auth: "api_key" },
  { slug: "MAILCHECK", name: "Mailcheck", cat: "email", auth: "api_key" },
  { slug: "MAILCOACH", name: "Mailcoach", cat: "marketing", auth: "api_key" },
  { slug: "MAILERCLOUD", name: "Mailercloud", cat: "marketing", auth: "api_key" },
  { slug: "MAILERSEND", name: "MailerSend", cat: "other", auth: "api_key" },
  { slug: "MAILS_SO", name: "Mails.so", cat: "email", auth: "api_key" },
  { slug: "MAILSOFTLY", name: "Mailsoftly", cat: "marketing", auth: "api_key" },
  { slug: "MAILTRAP", name: "Mailtrap", cat: "developer", auth: "bearer" },
  { slug: "MAKE", name: "Make", cat: "marketing", auth: "api_key" },
  { slug: "MANUS", name: "Manus", cat: "productivity", auth: "api_key" },
  { slug: "MAPBOX", name: "Mapbox", cat: "developer", auth: "api_key" },
  { slug: "MAPULUS", name: "Mapulus", cat: "developer", auth: "api_key" },
  { slug: "MARKETSTACK", name: "Marketstack", cat: "developer", auth: "api_key" },
  { slug: "MATTERPORT", name: "Matterport", cat: "developer", auth: "basic" },
  { slug: "MAXIO", name: "Maxio", cat: "other", auth: "api_key" },
  { slug: "MELO", name: "Melo", cat: "analytics", auth: "api_key" },
  { slug: "MEM", name: "Mem", cat: "notes", auth: "api_key" },
  { slug: "MEMBERSPOT", name: "Memberspot", cat: "education", auth: "api_key" },
  { slug: "MEMBERSTACK", name: "Memberstack", cat: "other", auth: "api_key" },
  { slug: "MEMBERVAULT", name: "Membervault", cat: "education", auth: "api_key" },
  { slug: "METABASE", name: "Metabase", cat: "other", auth: "api_key" },
  { slug: "METAPHOR", name: "Metaphor", cat: "ai", auth: "api_key" },
  { slug: "MEZMO", name: "Mezmo", cat: "other", auth: "api_key" },
  { slug: "ONENOTE", name: "Microsoft OneNote", cat: "productivity", auth: "oauth" },
  { slug: "MICROSOFT_POWER_BI", name: "Microsoft Power Bi", cat: "other", auth: "oauth" },
  { slug: "MINERSTAT", name: "Minerstat", cat: "other", auth: "api_key" },
  { slug: "MISSIVE", name: "Missive", cat: "email", auth: "api_key" },
  { slug: "MISTRAL_AI", name: "Mistral AI", cat: "ai", auth: "api_key" },
  { slug: "MIXMAX", name: "Mixmax", cat: "email", auth: "api_key" },
  { slug: "MOCO", name: "Moco", cat: "project", auth: "api_key" },
  { slug: "MODELRY", name: "Modelry", cat: "ecommerce", auth: "api_key" },
  { slug: "MONEYBIRD", name: "Moneybird", cat: "finance", auth: "oauth" },
  { slug: "MOONCLERK", name: "Moonclerk", cat: "payments", auth: "api_key" },
  { slug: "MOOSEND", name: "Moosend", cat: "marketing", auth: "api_key" },
  { slug: "MOTION", name: "Motion", cat: "productivity", auth: "api_key" },
  { slug: "MSG91", name: "Msg91", cat: "chat", auth: "api_key" },
  { slug: "MX_TECHNOLOGIES", name: "MX Technologies", cat: "developer", auth: "basic" },
  { slug: "MX_TOOLBOX", name: "MXToolbox", cat: "other", auth: "api_key" },
  { slug: "NANGO", name: "Nango", cat: "developer", auth: "api_key" },
  { slug: "NANO_NETS", name: "Nanonets", cat: "other", auth: "api_key" },
  { slug: "NASA", name: "Nasa", cat: "developer", auth: "api_key" },
  { slug: "NASDAQ", name: "Nasdaq", cat: "analytics", auth: "api_key" },
  { slug: "NEEDLE", name: "Needle", cat: "ai", auth: "api_key" },
  { slug: "NEO4J", name: "Neo4J", cat: "developer", auth: "oauth" },
  { slug: "NETHUNT_CRM", name: "NetHunt CRM", cat: "crm", auth: "basic" },
  { slug: "NEURONWRITER", name: "Neuronwriter", cat: "marketing", auth: "api_key" },
  { slug: "NEUTRINO", name: "Neutrino", cat: "developer", auth: "api_key" },
  { slug: "NEVERBOUNCE", name: "NeverBounce", cat: "email", auth: "api_key" },
  { slug: "NEW_RELIC", name: "New Relic", cat: "other", auth: "api_key" },
  { slug: "NEWS_API", name: "NewsAPI", cat: "news", auth: "api_key" },
  { slug: "NEXTDNS", name: "Nextdns", cat: "other", auth: "api_key" },
  { slug: "NIFTYIMAGES", name: "Niftyimages", cat: "marketing", auth: "api_key" },
  { slug: "NINOX", name: "Ninox", cat: "database", auth: "api_key" },
  { slug: "NOCODB", name: "NocoDB", cat: "database", auth: "api_key" },
  { slug: "NOCRM_IO", name: "NoCRM.io", cat: "crm", auth: "api_key" },
  { slug: "NORTHFLANK", name: "Northflank", cat: "developer", auth: "api_key" },
  { slug: "NOZBE_TEAMS", name: "Nozbe Teams", cat: "tasks", auth: "api_key" },
  { slug: "NPM", name: "Npm", cat: "developer", auth: "api_key" },
  { slug: "NTFY", name: "Ntfy", cat: "other", auth: "api_key" },
  { slug: "NUSII_PROPOSALS", name: "Nusii proposals", cat: "other", auth: "api_key" },
  { slug: "NUTSHELL", name: "Nutshell", cat: "crm", auth: "basic" },
  { slug: "OCR_WEB_SERVICE", name: "OCR Web Service", cat: "other", auth: "basic" },
  { slug: "OCRSPACE", name: "OCR.space", cat: "other", auth: "api_key" },
  { slug: "ODOO", name: "Odoo", cat: "crm", auth: "api_key" },
  { slug: "OKSIGN", name: "Oksign", cat: "signatures", auth: "api_key" },
  { slug: "OLLAMA", name: "Ollama", cat: "other", auth: "api_key" },
  { slug: "OMNISEND", name: "Omnisend", cat: "marketing", auth: "api_key" },
  { slug: "ONEDESK", name: "Onedesk", cat: "support", auth: "api_key" },
  { slug: "ONESIGNAL_REST_API", name: "OneSignal REST API", cat: "other", auth: "api_key" },
  { slug: "ONESIGNAL_USER_AUTH", name: "OneSignal User Auth", cat: "other", auth: "api_key" },
  { slug: "OPENAI", name: "OpenAI", cat: "ai", auth: "api_key" },
  { slug: "OPENCAGE", name: "Opencage", cat: "developer", auth: "api_key" },
  { slug: "OPENGRAPH_IO", name: "OpenGraph.io", cat: "scraping", auth: "api_key" },
  { slug: "OPENPERPLEX", name: "Openperplex", cat: "ai", auth: "api_key" },
  { slug: "OPENROUTER", name: "Openrouter", cat: "ai", auth: "api_key" },
  { slug: "OPENWEATHER_API", name: "OpenWeather API", cat: "developer", auth: "api_key" },
  { slug: "OPTIMOROUTE", name: "OptimoRoute", cat: "project", auth: "api_key" },
  { slug: "OUTLINE", name: "Outline", cat: "productivity", auth: "api_key" },
  { slug: "OWL_PROTOCOL", name: "Owl Protocol", cat: "developer", auth: "api_key" },
  { slug: "PAGE_X", name: "Page X", cat: "crm", auth: "api_key" },
  { slug: "PAPERFORM", name: "Paperform", cat: "forms", auth: "api_key" },
  { slug: "PARADYM", name: "Paradym", cat: "other", auth: "api_key" },
  { slug: "PARALLEL", name: "Parallel", cat: "scraping", auth: "api_key" },
  { slug: "PARMA", name: "Parma", cat: "crm", auth: "oauth" },
  { slug: "PARSEHUB", name: "Parsehub", cat: "scraping", auth: "api_key" },
  { slug: "PARSERA", name: "Parsera", cat: "scraping", auth: "api_key" },
  { slug: "PARSEUR", name: "Parseur", cat: "other", auth: "api_key" },
  { slug: "PARSIO_IO", name: "Parsio.io", cat: "other", auth: "api_key" },
  { slug: "PASSCREATOR", name: "Passcreator", cat: "other", auth: "api_key" },
  { slug: "PASSSLOT", name: "Passslot", cat: "other", auth: "api_key" },
  { slug: "PAYHERE", name: "Payhere", cat: "ecommerce", auth: "api_key" },
  { slug: "PAYHIP", name: "Payhip", cat: "ecommerce", auth: "api_key" },
  { slug: "PAYPAL", name: "Paypal", cat: "payments", auth: "oauth" },
  { slug: "PAYSTACK", name: "Paystack", cat: "payments", auth: "api_key" },
  { slug: "PDF_API_IO", name: "PDF-API.io", cat: "documents", auth: "api_key" },
  { slug: "PDF_CO", name: "PDF.co", cat: "documents", auth: "api_key" },
  { slug: "PDF4ME", name: "Pdf4me", cat: "documents", auth: "api_key" },
  { slug: "PDFLESS", name: "Pdfless", cat: "documents", auth: "api_key" },
  { slug: "PDFMONKEY", name: "PDFMonkey", cat: "documents", auth: "api_key" },
  { slug: "PENPOT", name: "Penpot", cat: "design", auth: "api_key" },
  { slug: "PERIGON", name: "Perigon", cat: "news", auth: "api_key" },
  { slug: "PERSISTIQ", name: "Persistiq", cat: "crm", auth: "api_key" },
  { slug: "PERSONA", name: "Persona", cat: "other", auth: "api_key" },
  { slug: "PEXELS", name: "Pexels", cat: "design", auth: "api_key" },
  { slug: "PHANTOMBUSTER", name: "PhantomBuster", cat: "scraping", auth: "api_key" },
  { slug: "PILOTERR", name: "Piloterr", cat: "scraping", auth: "api_key" },
  { slug: "PILVIO", name: "Pilvio", cat: "developer", auth: "api_key" },
  { slug: "PINECONE", name: "Pinecone", cat: "ai", auth: "api_key" },
  { slug: "PINGDOM", name: "Pingdom", cat: "other", auth: "api_key" },
  { slug: "PIPELINE_CRM", name: "Pipeline CRM", cat: "crm", auth: "api_key" },
  { slug: "PLACID", name: "Placid", cat: "design", auth: "api_key" },
  { slug: "PLAIN", name: "Plain", cat: "support", auth: "api_key" },
  { slug: "PLANLY", name: "Planly", cat: "other", auth: "api_key" },
  { slug: "PLANYO_ONLINE_BOOKING", name: "Planyo Online Booking", cat: "scheduling", auth: "api_key" },
  { slug: "PLASMIC", name: "Plasmic", cat: "other", auth: "api_key" },
  { slug: "PLATERECOGNIZER", name: "Plate Recognizer", cat: "ai", auth: "api_key" },
  { slug: "PLAUSIBLE_ANALYTICS", name: "Plausible Analytics", cat: "analytics", auth: "api_key" },
  { slug: "PLISIO", name: "Plisio", cat: "payments", auth: "api_key" },
  { slug: "POINTAGRAM", name: "Pointagram", cat: "productivity", auth: "api_key" },
  { slug: "POLYGON", name: "Polygon", cat: "analytics", auth: "api_key" },
  { slug: "POLYGON_IO", name: "Polygon.io", cat: "analytics", auth: "api_key" },
  { slug: "POLYMARKET_US", name: "Polymarket US", cat: "other", auth: "api_key" },
  { slug: "POLYMARKET", name: "Polymarket US", cat: "other", auth: "api_key" },
  { slug: "POOF", name: "Poof", cat: "payments", auth: "api_key" },
  { slug: "POSTALYTICS", name: "Postalytics", cat: "marketing", auth: "api_key" },
  { slug: "POSTGRID", name: "Postgrid", cat: "developer", auth: "api_key" },
  { slug: "POSTGRID_VERIFY", name: "PostGrid Verify", cat: "developer", auth: "api_key" },
  { slug: "POSTMAN", name: "Postman", cat: "developer", auth: "api_key" },
  { slug: "POSTMARK", name: "Postmark", cat: "other", auth: "api_key" },
  { slug: "PRERENDER", name: "Prerender", cat: "developer", auth: "api_key" },
  { slug: "PRINTAUTOPILOT", name: "Printautopilot", cat: "developer", auth: "api_key" },
  { slug: "PRISMA", name: "Prisma", cat: "database", auth: "oauth" },
  { slug: "PRISMIC", name: "Prismic", cat: "other", auth: "api_key" },
  { slug: "PROABONO", name: "Proabono", cat: "ecommerce", auth: "basic" },
  { slug: "PROCFU", name: "Procfu", cat: "developer", auth: "api_key" },
  { slug: "PRODUCTLANE", name: "Productlane", cat: "support", auth: "api_key" },
  { slug: "PROJECT_BUBBLE", name: "Project Bubble", cat: "project", auth: "api_key" },
  { slug: "PROMPTMATE_IO", name: "Promptmate.io", cat: "ai", auth: "api_key" },
  { slug: "PROOFLY", name: "Proofly", cat: "marketing", auth: "api_key" },
  { slug: "PROXIEDMAIL", name: "Proxiedmail", cat: "email", auth: "api_key" },
  { slug: "PUSH_BY_TECHULUS", name: "Push by Techulus", cat: "other", auth: "api_key" },
  { slug: "PUSHBULLET", name: "Pushbullet", cat: "other", auth: "oauth" },
  { slug: "PUSHOVER", name: "Pushover", cat: "other", auth: "api_key" },
  { slug: "QUADERNO", name: "Quaderno", cat: "other", auth: "api_key" },
  { slug: "QUICKBOOKS", name: "QuickBooks", cat: "finance", auth: "oauth" },
  { slug: "RADAR", name: "Radar", cat: "developer", auth: "api_key" },
  { slug: "RAGIC", name: "Ragic", cat: "database", auth: "api_key" },
  { slug: "RAGIE", name: "Ragie", cat: "developer", auth: "api_key" },
  { slug: "RAISELY", name: "Raisely", cat: "other", auth: "api_key" },
  { slug: "RAMP", name: "Ramp", cat: "finance", auth: "oauth" },
  { slug: "RAWG_VIDEO_GAMES_DATABASE", name: "RAWG Video Games Database", cat: "other", auth: "api_key" },
  { slug: "RAZORPAY", name: "Razorpay", cat: "payments", auth: "api_key" },
  { slug: "RE_AMAZE", name: "Re:amaze", cat: "support", auth: "api_key" },
  { slug: "REALPHONEVALIDATION", name: "Realphonevalidation", cat: "other", auth: "api_key" },
  { slug: "RECRUITEE", name: "Recruitee", cat: "other", auth: "api_key" },
  { slug: "REDCIRCLE_API", name: "RedCircle API", cat: "developer", auth: "api_key" },
  { slug: "REDDIT_ADS", name: "Reddit Ads", cat: "marketing", auth: "oauth" },
  { slug: "REFERRALROCK", name: "ReferralRock", cat: "marketing", auth: "basic" },
  { slug: "REFINER", name: "Refiner", cat: "forms", auth: "api_key" },
  { slug: "REMARKETY", name: "Remarkety", cat: "marketing", auth: "api_key" },
  { slug: "REMOTE_RETRIEVAL", name: "Remote Retrieval", cat: "other", auth: "api_key" },
  { slug: "REMOVE_BG", name: "Remove.bg", cat: "design", auth: "api_key" },
  { slug: "RENDER", name: "Render", cat: "developer", auth: "api_key" },
  { slug: "RENDERFORM", name: "Renderform", cat: "design", auth: "api_key" },
  { slug: "RENTMAN", name: "Rentman", cat: "productivity", auth: "api_key" },
  { slug: "REPAIRSHOPR", name: "RepairShopr", cat: "crm", auth: "api_key" },
  { slug: "REPLICATE", name: "Replicate", cat: "ai", auth: "api_key" },
  { slug: "REPLY", name: "Reply", cat: "marketing", auth: "api_key" },
  { slug: "REPLY_IO", name: "Reply.io", cat: "marketing", auth: "api_key" },
  { slug: "RESEND", name: "Resend", cat: "email", auth: "api_key" },
  { slug: "RESPOND_IO", name: "Respond.io", cat: "support", auth: "api_key" },
  { slug: "RETAILED", name: "Retailed", cat: "ecommerce", auth: "api_key" },
  { slug: "RETENTLY", name: "Retently", cat: "forms", auth: "api_key" },
  { slug: "REV_AI", name: "Rev AI", cat: "ai", auth: "api_key" },
  { slug: "REV", name: "Rev AI", cat: "other", auth: "api_key" },
  { slug: "REVOLT", name: "Revolt", cat: "chat", auth: "api_key" },
  { slug: "RITEKIT", name: "Ritekit", cat: "other", auth: "api_key" },
  { slug: "RIZE", name: "Rize", cat: "productivity", auth: "api_key" },
  { slug: "RKVST", name: "Rkvst", cat: "other", auth: "api_key" },
  { slug: "ROAM", name: "Roam", cat: "chat", auth: "api_key" },
  { slug: "ROBOFLOW", name: "Roboflow", cat: "ai", auth: "api_key" },
  { slug: "ROCKETADMIN", name: "Rocketadmin", cat: "developer", auth: "api_key" },
  { slug: "ROLLBAR", name: "Rollbar", cat: "developer", auth: "api_key" },
  { slug: "ROOTLY", name: "Rootly", cat: "other", auth: "api_key" },
  { slug: "ROSETTE_TEXT_ANALYTICS", name: "Rosette Text Analytics", cat: "ai", auth: "api_key" },
  { slug: "ROUTE4ME", name: "Route4me", cat: "project", auth: "api_key" },
  { slug: "RUDDERSTACK_TRANSFORMATION", name: "RudderStack Transformation", cat: "analytics", auth: "basic" },
  { slug: "RUNPOD", name: "RunPod", cat: "developer", auth: "api_key" },
  { slug: "SAFETYCULTURE", name: "SafetyCulture", cat: "forms", auth: "api_key" },
  { slug: "SALESFLARE", name: "Salesflare", cat: "crm", auth: "api_key" },
  { slug: "SALESFORCE_SERVICE_CLOUD", name: "Salesforce Service Cloud", cat: "crm", auth: "oauth" },
  { slug: "SALESMATE", name: "Salesmate", cat: "crm", auth: "api_key" },
  { slug: "SANITY", name: "Sanity", cat: "developer", auth: "api_key" },
  { slug: "SAP_SUCCESSFACTORS", name: "SAP SuccessFactors", cat: "other", auth: "api_key" },
  { slug: "SATISMETER", name: "Satismeter", cat: "forms", auth: "api_key" },
  { slug: "SAUCELABS", name: "Saucelabs", cat: "developer", auth: "basic" },
  { slug: "SCALE_AI", name: "Scale ai", cat: "ai", auth: "api_key" },
  { slug: "SCHEDULEONCE", name: "Scheduleonce", cat: "scheduling", auth: "api_key" },
  { slug: "SCRAPE_DO", name: "Scrape Do", cat: "scraping", auth: "api_key" },
  { slug: "SCRAPEGRAPH_AI", name: "Scrapegraph Ai", cat: "scraping", auth: "api_key" },
  { slug: "SCRAPFLY", name: "Scrapfly", cat: "scraping", auth: "api_key" },
  { slug: "SCRAPINGANT", name: "Scrapingant", cat: "scraping", auth: "api_key" },
  { slug: "SCRAPINGBEE", name: "Scrapingbee", cat: "scraping", auth: "api_key" },
  { slug: "SCREENSHOT_FYI", name: "Screenshot.fyi", cat: "developer", auth: "api_key" },
  { slug: "SEARCH_API", name: "Search api", cat: "developer", auth: "api_key" },
  { slug: "SEAT_GEEK", name: "Seat Geek", cat: "other", auth: "none" },
  { slug: "SECURITYTRAILS", name: "Securitytrails", cat: "other", auth: "api_key" },
  { slug: "SEGMENT", name: "Segment", cat: "analytics", auth: "api_key" },
  { slug: "SEGMETRICS", name: "Segmetrics", cat: "analytics", auth: "api_key" },
  { slug: "SENDBIRD", name: "Sendbird", cat: "chat", auth: "api_key" },
  { slug: "SENDBIRD_AI_CHABOT", name: "Sendbird AI Chatbot", cat: "other", auth: "api_key" },
  { slug: "SENDER", name: "Sender", cat: "marketing", auth: "api_key" },
  { slug: "SENDFOX", name: "Sendfox", cat: "marketing", auth: "api_key" },
  { slug: "SENDLANE", name: "Sendlane", cat: "marketing", auth: "api_key" },
  { slug: "SENDLOOP", name: "Sendloop", cat: "marketing", auth: "api_key" },
  { slug: "SENDSPARK", name: "Sendspark", cat: "video", auth: "api_key" },
  { slug: "SENSIBO", name: "Sensibo", cat: "other", auth: "api_key" },
  { slug: "SEQERA", name: "Seqera", cat: "developer", auth: "api_key" },
  { slug: "SERPDOG", name: "Serpdog", cat: "scraping", auth: "api_key" },
  { slug: "SERPHOUSE", name: "Serphouse", cat: "developer", auth: "api_key" },
  { slug: "SERPLY", name: "Serply", cat: "developer", auth: "api_key" },
  { slug: "SERVERAVATAR", name: "Serveravatar", cat: "developer", auth: "api_key" },
  { slug: "SEVDESK", name: "Sevdesk", cat: "finance", auth: "api_key" },
  { slug: "SHIPDAY", name: "Shipday", cat: "ecommerce", auth: "basic" },
  { slug: "SHIPENGINE", name: "Shipengine", cat: "ecommerce", auth: "api_key" },
  { slug: "SHIPPO", name: "Shippo", cat: "ecommerce", auth: "api_key" },
  { slug: "SHORT_IO", name: "Short Io", cat: "other", auth: "api_key" },
  { slug: "SHORT_MENU", name: "Short Menu", cat: "other", auth: "api_key" },
  { slug: "SHORTEN_REST", name: "Shorten.REST", cat: "other", auth: "api_key" },
  { slug: "SHORTPIXEL", name: "Shortpixel", cat: "design", auth: "api_key" },
  { slug: "SHOTSTACK", name: "Shotstack", cat: "video", auth: "api_key" },
  { slug: "SIDETRACKER", name: "Sidetracker", cat: "analytics", auth: "api_key" },
  { slug: "SIGNATURELY", name: "Signaturely", cat: "signatures", auth: "api_key" },
  { slug: "SIGNPATH", name: "Signpath", cat: "other", auth: "api_key" },
  { slug: "SIGNWELL", name: "Signwell", cat: "signatures", auth: "api_key" },
  { slug: "SIMILARWEB_DIGITALRANK_API", name: "SimilarWeb Digital Rank API", cat: "analytics", auth: "api_key" },
  { slug: "SIMLA_COM", name: "Simla.com", cat: "crm", auth: "api_key" },
  { slug: "SIMPLE_ANALYTICS", name: "Simple Analytics", cat: "analytics", auth: "api_key" },
  { slug: "SIMPLEKPI", name: "Simplekpi", cat: "analytics", auth: "basic" },
  { slug: "SIMPLERO", name: "Simplero", cat: "marketing", auth: "api_key" },
  { slug: "SITESPEAKAI", name: "Sitespeakai", cat: "other", auth: "api_key" },
  { slug: "SKYFIRE", name: "Skyfire", cat: "ai", auth: "api_key" },
  { slug: "SLITE", name: "Slite", cat: "documents", auth: "api_key" },
  { slug: "SMARTPROXY", name: "Smartproxy", cat: "scraping", auth: "api_key" },
  { slug: "SMS_ALERT", name: "SMS Alert", cat: "other", auth: "api_key" },
  { slug: "SMTP2GO", name: "Smtp2go", cat: "other", auth: "api_key" },
  { slug: "SNAPCHAT", name: "Snapchat", cat: "marketing", auth: "oauth" },
  { slug: "SNOWFLAKE_BASIC", name: "Snowflake Basic", cat: "database", auth: "basic" },
  { slug: "SOFTR", name: "Softr", cat: "other", auth: "api_key" },
  { slug: "SOLCAST", name: "Solcast", cat: "analytics", auth: "api_key" },
  { slug: "SOUNDCLOUD", name: "SoundCloud", cat: "video", auth: "oauth" },
  { slug: "SOURCEGRAPH", name: "Sourcegraph", cat: "developer", auth: "api_key" },
  { slug: "SPECIFIC", name: "Specific", cat: "other", auth: "api_key" },
  { slug: "SPLITWISE", name: "Splitwise", cat: "finance", auth: "oauth" },
  { slug: "SPOKI", name: "Spoki", cat: "marketing", auth: "api_key" },
  { slug: "SPONDYR", name: "Spondyr", cat: "documents", auth: "api_key" },
  { slug: "SPOTIFY", name: "Spotify", cat: "news", auth: "oauth" },
  { slug: "SPOTLIGHTR", name: "Spotlightr", cat: "video", auth: "api_key" },
  { slug: "SSLMATE_CERT_SPOTTER_API", name: "SSLMate Cert Spotter API", cat: "other", auth: "api_key" },
  { slug: "STACK_AI", name: "Stack Ai", cat: "ai", auth: "api_key" },
  { slug: "STANNP", name: "Stannp", cat: "marketing", auth: "api_key" },
  { slug: "STARTON", name: "Starton", cat: "developer", auth: "api_key" },
  { slug: "STATUSCAKE", name: "Statuscake", cat: "other", auth: "api_key" },
  { slug: "STOREGANISE", name: "Storeganise", cat: "ecommerce", auth: "api_key" },
  { slug: "STOREROCKET", name: "Storerocket", cat: "ecommerce", auth: "api_key" },
  { slug: "STORMBOARD", name: "Stormboard", cat: "productivity", auth: "api_key" },
  { slug: "STORMGLASS_IO", name: "Stormglass Io", cat: "developer", auth: "api_key" },
  { slug: "STORYBLOK", name: "Storyblok", cat: "developer", auth: "api_key" },
  { slug: "STRAVA", name: "Strava", cat: "other", auth: "oauth" },
  { slug: "STREAMTIME", name: "Streamtime", cat: "project", auth: "api_key" },
  { slug: "STUDIO_BY_AI21_LABS", name: "Studio By Ai21 Labs", cat: "other", auth: "api_key" },
  { slug: "SUITEDASH", name: "Suitedash", cat: "productivity", auth: "api_key" },
  { slug: "SUPADATA", name: "Supadata", cat: "scraping", auth: "api_key" },
  { slug: "SUPERCHAT", name: "Superchat", cat: "chat", auth: "api_key" },
  { slug: "SUPERSAAS", name: "Supersaas", cat: "scheduling", auth: "api_key" },
  { slug: "SUPPORTBEE", name: "Supportbee", cat: "support", auth: "api_key" },
  { slug: "SUPPORTIVEKOALA", name: "Supportivekoala", cat: "design", auth: "api_key" },
  { slug: "SVIX", name: "Svix", cat: "developer", auth: "api_key" },
  { slug: "SWAGGERHUB", name: "Swaggerhub", cat: "developer", auth: "api_key" },
  { slug: "SWARMSYNCAI", name: "Swarmsyncai", cat: "developer", auth: "api_key" },
  { slug: "SYMPLA", name: "Sympla", cat: "other", auth: "api_key" },
  { slug: "SYNTHFLOW_AI", name: "Synthflow AI", cat: "ai", auth: "api_key" },
  { slug: "TAGGUN", name: "Taggun", cat: "other", auth: "api_key" },
  { slug: "TALENTHR", name: "Talenthr", cat: "other", auth: "api_key" },
  { slug: "TALLY", name: "Tally", cat: "forms", auth: "api_key" },
  { slug: "TAPFILIATE", name: "Tapfiliate", cat: "marketing", auth: "api_key" },
  { slug: "TAVE", name: "Tave", cat: "crm", auth: "api_key" },
  { slug: "TAXJAR", name: "Taxjar", cat: "other", auth: "api_key" },
  { slug: "TEAMCAMP", name: "Teamcamp", cat: "project", auth: "api_key" },
  { slug: "TELEGRAM", name: "Telegram", cat: "chat", auth: "api_key" },
  { slug: "TELNYX", name: "Telnyx", cat: "other", auth: "api_key" },
  { slug: "TELTEL", name: "Teltel", cat: "other", auth: "api_key" },
  { slug: "TEMPLATED", name: "Templated", cat: "design", auth: "api_key" },
  { slug: "TEST_APP", name: "Test app", cat: "other", auth: "none" },
  { slug: "TEXTCORTEX", name: "Textcortex", cat: "ai", auth: "api_key" },
  { slug: "TEXTIT", name: "Textit", cat: "other", auth: "api_key" },
  { slug: "THANKS_IO", name: "Thanks.io", cat: "marketing", auth: "api_key" },
  { slug: "THE_ODDS_API", name: "The Odds API", cat: "other", auth: "api_key" },
  { slug: "TICKETMASTER", name: "Ticketmaster", cat: "other", auth: "api_key" },
  { slug: "TICKTICK", name: "Ticktick", cat: "productivity", auth: "oauth" },
  { slug: "TIDY", name: "Tidy", cat: "scheduling", auth: "api_key" },
  { slug: "TIKTOK", name: "Tiktok", cat: "social", auth: "oauth" },
  { slug: "TIMELINESAI", name: "TimelinesAI", cat: "chat", auth: "api_key" },
  { slug: "TIMELINK", name: "Timelink", cat: "other", auth: "api_key" },
  { slug: "TLDV", name: "Tldv", cat: "productivity", auth: "api_key" },
  { slug: "TOGGL", name: "Toggl", cat: "other", auth: "api_key" },
  { slug: "TOKEN_METRICS", name: "Token Metrics", cat: "analytics", auth: "api_key" },
  { slug: "TOMBA", name: "Tomba", cat: "other", auth: "api_key" },
  { slug: "TOMTOM", name: "Tomtom", cat: "developer", auth: "api_key" },
  { slug: "TPSCHECK", name: "Tpscheck", cat: "marketing", auth: "api_key" },
  { slug: "TRIGGERCMD", name: "Triggercmd", cat: "developer", auth: "api_key" },
  { slug: "TRIPADVISOR", name: "Tripadvisor", cat: "other", auth: "api_key" },
  { slug: "TRIPADVISOR_CONTENT_API", name: "TripAdvisor Content API", cat: "other", auth: "api_key" },
  { slug: "TRUVERA", name: "Truvera", cat: "other", auth: "api_key" },
  { slug: "TURBOT_PIPES", name: "Turbot Pipes", cat: "developer", auth: "api_key" },
  { slug: "TURSO", name: "Turso", cat: "database", auth: "api_key" },
  { slug: "TWELVE_DATA", name: "Twelve Data", cat: "analytics", auth: "api_key" },
  { slug: "TWOCAPTCHA", name: "Twocaptcha", cat: "developer", auth: "api_key" },
  { slug: "TYPEFORM", name: "Typeform", cat: "forms", auth: "oauth" },
  { slug: "TYPLESS", name: "Typless", cat: "other", auth: "api_key" },
  { slug: "U301", name: "U301", cat: "other", auth: "api_key" },
  { slug: "UNIONE", name: "Unione", cat: "other", auth: "api_key" },
  { slug: "UNISENDER", name: "Unisender", cat: "marketing", auth: "api_key" },
  { slug: "UNISWAP_API", name: "Uniswap Api", cat: "developer", auth: "api_key" },
  { slug: "UPDOWN_IO", name: "Updown.io", cat: "other", auth: "api_key" },
  { slug: "UPLOADCARE", name: "Uploadcare", cat: "storage", auth: "api_key" },
  { slug: "UPTIMEROBOT", name: "Uptimerobot", cat: "other", auth: "api_key" },
];

export async function OPTIONS() { return new NextResponse(null, { status: 204, headers: cors }); }

// The payload is a compile-time constant (~70 KB) and the app refetches it on every refresh, so
// let it be cached rather than re-serialized by a Node lambda each time.
export async function GET() {
  return NextResponse.json(
    { apps: APPS },
    { headers: { ...cors, "Cache-Control": "public, max-age=3600, stale-while-revalidate=86400" } }
  );
}
